# Generated by Django 3.0.8 on 2020-07-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
    ]
